spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_spring_jpa?currentSchema=test_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: supersecret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/test_spring_jpa
    user: postgres
    password: supersecret
    schemas: test_db
    baseline-on-migrate: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace    # this logs the parameters in the queries (to be used only in dev)